GET https://effus-apis.herokuapp.com/meetapi/1.0.0/user

### 

GET https://effus-apis.herokuapp.com/meetapi/1.0.0/user/5e4af0fbc633dd0004fe265c


###

PUT https://effus-apis.herokuapp.com/meetapi/1.0.0/user
content-type: application/json

{
    "email": "test@email.com",
    "name": "Name1",
    "password": "abcdef"
}