### Get user by auth token
http://localhost:5000/datesimapi/1.0.0/user/me
Authorization: token 5e6a3a521969aa5a941b11af:2dd661550c57302f2f164d5c6f57163567bc159bacfd03fce4fbb2c3a30f5b83

### Get user by auth token (prod)
https://effus-apis.herokuapp.com/datesimapi/1.0.0/user/me
Authorization: token 5e6a3de773a3d70004ca9762:51f8bfdb40c327646bbda3d7ce7b2bf975bbd6c2892b1a2d50dad7844568737e

### Register new user
PUT http://localhost:5000/datesimapi/1.0.0/user/register
content-type: application/json

{
    "email": "test4@email.com",
    "name": "test4",
    "password": "abcdef"
}

### Register new user (prod)
PUT https://effus-apis.herokuapp.com/datesimapi/1.0.0/user/register
content-type: application/json

{
    "email": "test1@email.com",
    "name": "test1",
    "password": "abc1def2"
}

### Register new user
POST http://localhost:5000/datesimapi/1.0.0/user/login
content-type: application/json

{
    "email": "test4@email.com",
    "password": "abcdef"
}

### login

POST http://localhost:5000/datesimapi/1.0.0/user/login
Content-Type: application/json;charset=UTF-8

{"email": "test4@email.com", "password": "123123123"}


### new bot

PUT http://localhost:5000/datesimapi/1.0.0/bot/
Content-Type: application/json;charset=UTF-8
Authorization: token 5e6ba5bd92d0810f4e579ba0:1584731987798:ddae5712864b884a140c87faeedfbd5b1eb7e026c50be342a82b05a1c02158fb

{"name": "456", "gender": "Female", "photo": ""}

### list created bots

GET http://localhost:5000/datesimapi/1.0.0/bot/own/5e750669037df7267e21c6a0
Content-Type: application/json;charset=UTF-8
Authorization: token 5e6ba5bd92d0810f4e579ba0:1584731987798:ddae5712864b884a140c87faeedfbd5b1eb7e026c50be342a82b05a1c02158fb


### buy bot

POST http://localhost:5000/datesimapi/1.0.0/bot/market/5e763b23733d443d61256525/buy
Content-Type: application/json;charset=UTF-8
Authorization: token 5e6ba5bd92d0810f4e579ba0:1584857790491:004091d5ac89c558fdf8b9f14a13c12510b2a9fadf5b9554bdb61edc6a7cb6e1


### list added bots
GET http://localhost:5000/datesimapi/1.0.0/bots/
Content-Type: application/json;charset=UTF-8
Authorization: token 5e9eb66a03d42e67c36cb14f:1588608004700:463c1e3057cb81e6119d9c71747ca3cb1e8d9c25425e6b5e1b63b06866aca209



### post bot messages
POST http://localhost:5000/datesimapi/1.0.0/bot/own/5e81f8b5044bf9157769063c/messages
Content-Type: application/json;charset=UTF-8
Authorization: token 5e81efb5440f3f1241968032:1585760771072:9187692726a16451a9b3daa39940e73f2079381b48dd58c2d2d57bed4f859e6a

{"messages":[{"id":81306,"text":"?","cases":[{"id":82386,"points":2,"text":"Hi!"},{"id":5017,"points":4,"text":"Shit!"}],"next":[{"id":81307,"points":0,"goto":"86194"},{"id":24345,"points":4,"goto":"10090"}]},{"id":86194,"text":"Hey!","cases":[],"next":[{"id":86194,"points":0,"goto":":finish:"}]},{"id":10090,"text":"Yea.. Its funny","cases":[],"next":[{"id":10090,"points":0,"goto":":finish:"}]}]}


### get chat for bot

GET http://localhost:5000/datesimapi/1.0.0/bot/chat/5e85dfdf360b7818f25c65b4
Content-Type: application/json;charset=UTF-8
Authorization: token 5e85df94360b7818f25c65b3:1586345990438:25d25f67588412f7eab9d05825c8fcad06accaff7fe172633426c2ddaf7188e1

### post chat case

POST http://localhost:5000/datesimapi/1.0.0/bot/chat/5e85dfdf360b7818f25c65b4
Content-Type: application/json;charset=UTF-8
Authorization: token 5e85df94360b7818f25c65b3:1586345990438:25d25f67588412f7eab9d05825c8fcad06accaff7fe172633426c2ddaf7188e1

{"caseId":34915,"attach":null}


### get added bot status

GET http://localhost:5000/datesimapi/1.0.0/bot/status/5eafdcd38912f23656407c5d
Content-Type: application/json;charset=UTF-8
Authorization: token 5e9eb66a03d42e67c36cb14f:1588610264204:a810b932cfc8e4d7cbe7104dcbb60d25f0a0a161df3c9cef8e520a224116b17e

### get added bot chat

GET http://localhost:5000/datesimapi/1.0.0/bot/chat/5eafdcd38912f23656407c5d
Content-Type: application/json;charset=UTF-8
Authorization: token 5e9eb66a03d42e67c36cb14f:1588610264204:a810b932cfc8e4d7cbe7104dcbb60d25f0a0a161df3c9cef8e520a224116b17e
